Pharmacy - Pharmaceuticals part 1
informatici/openhospital-ui pull request #221
Opened 2022-01-12 20:17 UTC by aldaprile

2022-01-18 07:25 UTC, tsognong commented
@aldaprile please is your pull request [https://github.com/informatici/openhospital-ui/pull/221](url) reviewable? Please give me a response as soon as possible.
Also you should align your work with the actual develop branch.

2022-01-18 11:00 UTC, tsognong requested changes

2022-01-20 09:58 UTC, axelpezzo commented
Hello guys, first of all thanks in advance for your work regarding the Pharmacy section. Let me introduce @almeida1492, @tsognong and me that we are the current dev team of this project.

I want to point out few things in order to make your code compliant with the Open Hospital standards.

In the past few weeks we reviewed your work and we point out some things that you should change, in particular:

- when a Pull Request is not ready, you must marker it "as draft".
- in order to make the code base clean and maintenable, you should use --when it's possibile-- the OH components already developed (eg. the Table component that @tsognong pointeed out).
- also, we use hook to the Redux logic. So, you should switch from the old logic to the new one. (you will find how to use this logic all around project).
- also, keep in mind that this is a open source project with a team that is responsible to maintein and develop new features. So, when you submit a Pull Request of your work, this will be reviewd everytime. This is a best practice to keep the code secure and compliant. Be proactive when we'll review your code, in order to make this step as flexible as possibile.

Furthermore, I want to submit to you some giudeline references:

https://openhospital.atlassian.net/wiki/spaces/OH/pages/6946820/Contribution+Guidelines
https://oh2.open-hospital.org/oh20-developer-portal/

For any other suggestion we are at your disposal, just write here.

2023-05-15 13:24 UTC, mwithi commented
Hello all, has anyone in his/her hand this work? Is it possible to resume/continue it? Thanks!

2026-03-12 15:56 UTC, mwithi commented
@SteveGT96 I think this work will be replaced by a new one, am I right? If so, please close this PR. Thanks a lot!

2026-03-16 10:47 UTC, SteveGT96 commented
@mwithi , you could close this, we will create PR for pharmacy works.

2026-03-16 15:56 UTC, closed without merging