OH2-133 | Implement permission logic
informatici/openhospital-ui pull request #336
Opened 2022-09-06 08:51 UTC by SteveGT96

2022-09-22 08:25 UTC, axelpezzo commented on src/components/accessories/alertBox/consts.ts
> +}));
We're not gonna use Styled Components as long as I remember. 

If you need to customize some styles based on props please wrape the Alert Material UI Component with a custom OH component and pass to him the props.

If you need some further customized style add a .scss file.

2022-09-22 08:30 UTC, axelpezzo commented on src/components/accessories/laboratory/EditLaboratoryContent.tsx
> +            creationMode ? ["exam.create"] : ["exam.read", "exam.update"]
Do we need the read permission in order to show the examform in edit mode?

2022-09-22 08:31 UTC, axelpezzo commented on src/components/accessories/laboratory/EditLaboratoryContent.tsx
> +            creationMode ? ["exam.create"] : ["exam.read", "exam.update"]
BEside, if we already start with the usePermission hook I think that would be great to keep the same pattern as long as possibile inside the component.

2022-09-22 08:31 UTC, axelpezzo commented on src/components/accessories/laboratory/Exams.tsx
> +            </PermissionWrapper>
As before, keep the same pattern.

2022-09-22 08:34 UTC, axelpezzo commented on src/components/accessories/permissionWrapper/PermissionWrapper.tsx
> +};
We already implemented a wrapper component called "Permission.tsx" inside libraries/permissionUtils.

Why did you need to create another one?

2022-09-22 08:42 UTC, axelpezzo commented on src/components/activities/newPatientActivity/NewPatientActivity.tsx
> +              <div ref={infoBoxRef}>
I think that the wrapper's position is in the wrong place. I mean the patient create permission should check in three different points:
- new patient button inside the patient dashboard.
- new patient route (some control that prevent the user to access to that route)
- a check inside the form page (it's useless in due to the two previous check but I think would be great to have this too). 

The third check should wrap the entire page's UI and not only the form it's self.

2022-09-22 08:43 UTC, axelpezzo commented on src/components/accessories/laboratory/Exams.tsx
>              <EditLaboratoryContent />
I think that even /new and /edit path sould be wrapped

2022-09-22 08:44 UTC, axelpezzo commented on src/components/accessories/laboratory/Exams.tsx
> +            </PermissionWrapper>
I think that even /new and /edit path sould be wrapped

2022-09-22 08:46 UTC, axelpezzo commented on src/components/accessories/patientOPD/patientOPD.tsx
> +
The "open" name is too much misleading, please rename it in something more contextual here and in the other files.

2022-09-22 08:47 UTC, axelpezzo commented on src/components/accessories/patientVisit/patientVisit.tsx
> +
As before

2022-09-22 08:50 UTC, axelpezzo commented on src/components/activities/editPatientActivity/EditPatientActivity.tsx
> +              </PermissionWrapper>
I think that all the jsx should be wrapped inside the permission check component. It's not wrong leave as is but I prefer that all the "protected" component (even If I cannot access to them directly as for example a modal) be stay under the wrapper. 

Please follow this here and in the other files.

2022-09-22 09:09 UTC, axelpezzo commented on src/components/activities/patientDetailsActivity/PatientDetailsActivity.tsx
> +  const canEdit = usePermission("patient.update");
I should check if I can access to this page too (something like If I don't have any permission or if I don't have the read permission to the patient).

2022-09-22 09:13 UTC, axelpezzo commented on src/components/activities/patientDetailsActivity/PatientDetailsActivity.tsx
> +                          ]}
I think that is more simple wrap each component with a Permission checker, don't you?

2022-09-22 09:13 UTC, axelpezzo commented on src/components/activities/patientDetailsActivityContent/PatientDetailsActivityContent.tsx
> +        )}
See before.

2022-09-22 09:17 UTC, axelpezzo commented on src/libraries/permissionUtils/useMultiplePermissions
> +};
I'm not sure what the purpose of this.

2022-10-19 09:34 UTC, axelpezzo commented
@SteveGT96 few notes I've noticed:

- When I try to access to a protected route and I haven't the permission to access to it, an error message should be shown on the UI (only for the route and not for each singole component as for example table or form)
- If I haven't the permission to edit and delete an element now in the table list I see an empty column, this should be handled by the Table component in order to hide it.
- If I haven't the permission to create an entity now I can't even edit his items clicking on the edit button on the table: the form still hiden.
- If i haven't the patient route permission I shoudn't be redirect to /patient when I login to the application (the same for the link on the OH logo, now it redirect me to the /patient route). I think that this could be solved by a whitelabel route (e.g. /) that check the permission and redirect me to the first route available.
- If I haven't the permission of read the patient I shouldn't be able to browser them inside the filter patient in /visit & /laboratory routes.

2023-01-19 10:18 UTC, alefalezza reviewed
@SteveGT96  please check my comments

2023-01-19 10:18 UTC, alefalezza commented on src/components/activities/visitsActivity/VisitsActivity.tsx
> +import { CustomPermissionDenied } from "../../accessories/customPermissionDenied/CustomPermissionDenied";
Unused?

2023-01-19 10:18 UTC, alefalezza commented on src/mockServer/fixtures/permissionList.js
> +  "visit.read",
Please ensure to use the same naming used in the backend

2023-01-19 10:18 UTC, alefalezza commented on src/libraries/permissionUtils/usePermission.ts
> +  if (!process.env.ENABLE_PERMISSIONS) {
Please declare this variable also in the .env file, in order to expose this option. I would prefer permissions to e enabled by default.

2023-01-19 10:18 UTC, alefalezza reviewed
@Steve please check my comments

2023-01-19 10:21 UTC, SteveGT96 commented
> 

OK !

2023-01-23 11:03 UTC, alefalezza commented on src/components/accessories/patientTriage/PatientTriage.tsx
> +import { usePermission } from "../../../libraries/permissionUtils/usePermission";
To remove.

2023-01-23 11:03 UTC, alefalezza commented on src/components/accessories/patientVisit/patientVisit.tsx
> +  useMemo,
Remove

2023-01-23 11:03 UTC, alefalezza commented on src/components/accessories/patientVisit/patientVisit.tsx
> +import { usePermission } from "../../../libraries/permissionUtils/usePermission";
Remove

2023-01-23 11:03 UTC, alefalezza commented on src/components/accessories/permissionWrapper/PermissionWrapper.tsx
> +import React, { FC } from "react";
It should be removed in favour of Permission component

2023-01-23 11:03 UTC, alefalezza reviewed
Please resolve all comments

2023-01-26 14:51 UTC, alefalezza requested changes

2023-01-26 14:51 UTC, alefalezza commented on src/components/accessories/patientOPD/patientOPD.tsx
>    const { t } = useTranslation();
At line 46:
```
const [deletedObjCode, setDeletedObjCode] = useState("");
```

Is not used, can we remove it?

2023-01-27 16:42 UTC, merged