OH2-154 | Dashboard first layout
informatici/openhospital-ui pull request #355
Opened 2022-11-04 08:28 UTC by SteveGT96

2022-11-11 14:41 UTC, alefalezza commented
There are many more changes than expected, please make sure there are no regressions

2023-01-24 09:07 UTC, alefalezza requested changes

2023-01-24 09:07 UTC, alefalezza commented on src/routes/MainRouter.tsx
> +        <Route index element={<Navigate to="/dashboard" replace />} />
Restore default navigation to /patients.
Add a link to dashboard in AppHeader menu

2023-01-24 09:07 UTC, alefalezza commented on src/resources/i18n/en.json
> +    "agetype": {
AgeType is duplicated, please remove entry at line 92

2023-01-24 10:41 UTC, SteveGT96 commented on src/generated/apis/AdmissionControllerApi.ts
> -    getAdmissionsUsingGET({ id }: GetAdmissionsUsingGETRequest): Observable<AdmissionDTO>
getAdmissionUsingGet is used to fetch a single admission by its id, whereas getAdmissionsUsingGet is used to fetch a list of admissions that match the provided query parameters(patientcode, admissionrange or dischargerange).

2023-01-26 14:06 UTC, alefalezza requested changes

2023-01-26 15:32 UTC, SteveGT96 commented on src/components/accessories/dateRangeField/DateRangeField.tsx
> +      onChange={handleDateChange}
I left onChange empty and I passed the onChangeHandler to the onAccept prop(to avoid render even when range start range is selected on the picker.

2023-01-27 11:25 UTC, alefalezza approved these changes

2023-01-27 13:09 UTC, merged