OHCS63 | Fix issue with age type contextual age range list box
informatici/openhospital-ui pull request #431
Opened 2023-01-09 14:43 UTC by SilverD3

Added english translations for age types

2023-01-17 14:13 UTC, almeida1492 requested changes

2023-01-17 14:13 UTC, almeida1492 commented on src/components/accessories/patientDataForm/PatientDataForm.tsx
> +  console.log(ageRangeOptions);
Please, remove the log.

2023-01-17 14:13 UTC, almeida1492 commented on src/resources/i18n/en.json
> +      "elderly": "Elderly"
These labels could be under the property `patient`. We should avoid unnecessary nesting like this.

2023-01-24 11:33 UTC, axelpezzo approved these changes

2023-01-24 15:12 UTC, merged