OH2-146 | Implement per-role landing page
informatici/openhospital-ui pull request #478
Opened 2023-06-02 10:29 UTC by SteveGT96

2023-06-07 09:41 UTC, alefalezza commented
In my opinion it's ok, but I would suggest to push configurability a little forward.
What if dashboard url and priority should be configurable in `/src/customization` folder?

Example: add a new configuration file in `/src/customization/landingPage`:
```typescript
type TLandingPagePriority = {
  permission: TPermission,
  route: string
}

// Landing page will be the first route matching permission,
// you can change priority rules by moving elements in this list
export const landingPagePriority = [
  {
    permission: "dashboard.access",
    route: "/dashboard"
  },
  {
    permission: "patient.access",
    route: "/patients"
  }
  // ... and so on
]
```

Then, in `src/libraries/hooks/useLandingPageRoute.ts`:

```typescript
// ...
// return the first route matching permissions
const landingPage = useMemo(
 () => landingPagePriority.find((element) => permissions.includes(element.permission)),
 [landingPagePriority, permissions]
);

return landingPage.route;
```

2023-06-07 09:43 UTC, alefalezza requested changes
My suggestions in comments

2023-06-08 07:31 UTC, axelpezzo commented on src/libraries/hooks/useLandingPageRoute.ts
> +    return null;
It is not an error just a code reading improvement: switch from an If / Else case to a Switch case.

2023-06-12 12:45 UTC, axelpezzo commented
@SilverD3 upon the Alessandro comment, I will suggest to remove the successRoute property on the RedirectAfterLogin component because could be lead to some misunderstanding. I suggesto to create a defaultRoute in the outer const.ts file and use that constant as default on the useLandingPageRoute result.

2023-06-19 08:34 UTC, SteveGT96 commented
Hello @alefalezza , @axelpezzo ! Sorry for replying late ! I've been on vacations. I did not know you didn't know. I just resolved your comments.

2023-06-20 07:56 UTC, alefalezza commented on src/routes/const.ts
> +export const defaultRoute = "/patients";
@SteveGT96 I would suggest to move this const to /customization/landingPage.ts, because it can be customized and is related to route configuration.

2023-06-20 09:06 UTC, mwithi approved these changes
Approving after peer reviews

2023-06-20 09:06 UTC, merged