OH2-209 | Align frontend with the backend
informatici/openhospital-ui pull request #490
Opened 2023-07-11 10:36 UTC by SteveGT96

Replace the api spec file in the frontend with the one generated by the backend.

2023-07-11 10:39 UTC, SteveGT96 commented
Hello @mwithi , @alefalezza , @axelpezzo , @almeida1492. This is ready for review.

2023-07-12 22:48 UTC, mwithi commented on src/generated/runtime.ts
Please add again changes in 0b7123722bfd4ecf772304f78c274b067bd93937

2023-07-12 22:51 UTC, mwithi requested changes
Please review the comments

2023-07-13 09:24 UTC, mwithi approved these changes

2023-07-17 07:45 UTC, merged