OH2-211 - OH2-212 - OH2-213 |Fix minor bugs on Patient OPD ~ Operation
informatici/openhospital-ui pull request #492
Opened 2023-07-17 14:00 UTC by SteveGT96

See OH2-211, OH2-212 and OH2-213

2023-07-17 16:57 UTC, gasp commented on src/components/accessories/patientOperation/operationForm/types.ts
> +  heideResultField?: boolean;
```suggestion
  hideResultField?: boolean;
```

2023-07-18 07:41 UTC, mwithi requested changes
See comments.

OH2-213 states also "I would suggest to also rename the checkbox in "Add another operation""

After that it LGTM.

2023-07-18 10:13 UTC, SteveGT96 commented
> See comments.
> 
> [OH2-213](https://openhospital.atlassian.net/browse/OH2-213) states also "I would suggest to also rename the checkbox in "Add another operation""
> 
> We may want to remove "Results" also from Clinical data ![image](https://user-images.githubusercontent.com/2938553/254182907-98263e88-92aa-4441-8f36-bea438f71471.png)
> 
> After that it LGTM.

Hello @mwithi ! I've also remove results for exams in clinic !

2023-07-24 14:50 UTC, mwithi approved these changes

2023-07-24 14:50 UTC, merged