OH2-222 | Align with they latest api spec file and add ward in visit form and table
informatici/openhospital-ui pull request #507
Opened 2023-08-08 09:45 UTC by SteveGT96

2023-08-14 08:49 UTC, mwithi requested changes
It seems ok, but please remove also the "+ CREATE NEW OPD VISIT” button

2023-09-13 10:33 UTC, mwithi commented
Up!

2023-09-18 14:57 UTC, mwithi commented
I think header is ok (we should think about how to change the logo though)

![image](https://github.com/informatici/openhospital-ui/assets/2938553/b741fe43-66ef-4718-ac45-13620a1a3e18)

pay attention that long notes are not wrapped and scrollbars should be avoided, as well as untranslated labels (see _angal.lab.blood.txt_)

![image](https://github.com/informatici/openhospital-ui/assets/2938553/e69ae490-cc0c-413f-8ba4-9e2e1255e6f7)

2023-09-18 14:58 UTC, mwithi commented
Also, seems there are conflicts with `src/styles/index.scss`

2023-09-21 14:02 UTC, mwithi commented on src/generated/runtime.ts
`withCredentials` has to stay

2023-09-21 15:08 UTC, mwithi commented on src/generated/apis/LoginApiApi.ts
why so many files are deleted?

2023-09-21 16:29 UTC, SteveGT96 commented on src/generated/apis/LoginApiApi.ts
When I was working on the task, I replaced the api file with the one provided by the backend.

2023-09-22 16:25 UTC, merged