OH2-296 | Vaccine list
informatici/openhospital-ui pull request #586
Opened 2024-05-22 15:22 UTC by SilverD3

See [OH2-296](https://openhospital.atlassian.net/browse/OH2-296)

2024-05-23 08:07 UTC, SteveGT96 requested changes
Unit tests failed

2024-05-23 08:07 UTC, SteveGT96 commented on src/components/accessories/admin/vaccines/vaccinesTable/VaccinesTable.tsx
> +            );
Filter is missing. Please take a look at the [mock-up](https://w6nt6m.axshare.com/?code=373a8db2aee9ac436955a60fb179b091&id=ijpxg2&p=vaccines).

2024-05-23 08:08 UTC, SteveGT96 commented on src/components/accessories/admin/vaccines/vaccinesTable/VaccinesTable.tsx
> +            );
Please, align with develop

2024-05-23 12:12 UTC, gasp commented
> Unit tests failed

It looks like the test failed because of a ECONNRESET. This is usually resolved by re-running the test.

2024-05-28 08:20 UTC, SteveGT96 requested changes

2024-05-28 08:20 UTC, SteveGT96 commented on src/components/accessories/admin/vaccines/vaccinesTable/VaccinesTable.tsx
> +    { key: "type", label: t("vaccine.vaccinetype"), type: "text" },
I would be better to handle "type" filter as a select, you could provide the vacines types as options.  You could also refer to existing filters.

2024-05-28 16:48 UTC, mwithi commented
@SilverD3 please resolve conflicts also (I think it is the topic suggested by @gasp on [Slack](https://join.slack.com/t/openhospitalworkspace/shared_invite/zt-cg9iu1d0-sjTuWWziFgcDqiTWyMJBAw))

2024-06-03 14:49 UTC, mwithi commented on src/components/accessories/admin/vaccines/vaccinesTable/VaccinesTable.tsx
> +    { key: "type", label: t("vaccine.vaccinetype"), type: "text" },
@SilverD3 can you do this?

2024-06-07 15:23 UTC, mwithi commented
Is it correct I don't see yet filter values for the type?

![Uploading image.png…]()

2024-06-07 15:39 UTC, SilverD3 commented
If you're using the backend, maybe it's because of the disability to fetch vaccines types.
With the mock data it's okay.
![vaccines (2)](https://github.com/informatici/openhospital-ui/assets/58907550/aad41ada-fed7-4f04-8d36-24897b7eb606)

2024-06-07 15:40 UTC, mwithi approved these changes
LGTM. Thanks a lot!

2024-06-07 15:40 UTC, merged