OH2-305 | Suppliers create and update
informatici/openhospital-ui pull request #596
Opened 2024-05-29 16:57 UTC by SilverD3

The API doesn't provide any endpoint for suppliers deletion, so the delete feature isn't include in this PR.

See OH2-305

2024-05-29 17:18 UTC, mwithi commented
> The API doesn't provide any endpoint for suppliers deletion, so the delete feature isn't include in this PR.

for suppliers we have soft-deletion (updateSupplier with SUP_DELETED='Y') I don't know why supDeleted has not been mapped in the DTO, could you open an issue for that in OP project?

2024-05-30 07:49 UTC, SilverD3 commented
@mwithi There are too many boards in the OP project. In which one should open the issue ?

2024-06-03 14:46 UTC, mwithi commented
> @mwithi There are too many boards in the OP project. In which one should open the issue ?

this one now has conflict, please I've no time to review all of them, let me ask @SteveGT96

2024-06-04 13:19 UTC, SteveGT96 requested changes
Now we are prefixing admin paths with "admin_" and we are reusing defined paths anywhere wanna navigate(navigate(PATHS....)

Please, could you align also ? Could check othe PRs to see.

2024-06-04 13:19 UTC, SteveGT96 commented on src/components/accessories/admin/suppliers/editSupplier/EditSupplier.tsx
> +      navigate(PATHS.suppliers);
```suggestion
      navigate(PATHS.admin_suppliers);
```

2024-06-04 13:19 UTC, SteveGT96 commented on src/components/accessories/admin/suppliers/Suppliers.tsx
> +            navigate("./new");
```suggestion
            navigate(PATHS.admin_suppliers_new);
```

2024-06-04 13:19 UTC, SteveGT96 commented on src/consts.ts
> +  suppliers_edit: "/admin/suppliers/:id/edit",
```suggestion
  admin_suppliers: "/admin/suppliers",
  admin_suppliers_new: "/admin/suppliers/new",
  admin_suppliers_edit: "/admin/suppliers/:id/edit",
```

2024-06-05 10:52 UTC, SteveGT96 approved these changes

2024-06-05 12:30 UTC, mwithi approved these changes
Approved by @SteveGT96

2024-06-05 12:30 UTC, merged

2024-06-05 13:23 UTC, mwithi commented
Do we need new permissions for the new page?

![image](https://github.com/informatici/openhospital-ui/assets/2938553/27ba55d5-8cd5-4f18-83c5-422656e69456)

2024-06-06 08:21 UTC, gasp commented
Good catch @mwithi , issuing a fix immediately: https://github.com/informatici/openhospital-ui/pull/600

2024-06-07 17:01 UTC, mwithi commented
> @mwithi There are too many boards in the OP project. In which one should open the issue ?

The board is the [OH2 Kanban](https://openhospital.atlassian.net/jira/software/c/projects/OH2/boards/12) but the issue has already been opened and backend side done, see OH2-310.