OH2-295 | Types / Operation CRUD
informatici/openhospital-ui pull request #605
Opened 2024-06-10 16:55 UTC by SilverD3

See OH2-295

2024-06-11 07:15 UTC, mwithi requested changes
It performs a fake deletion, because OS is actually used and if I come back to the page the deleted record is still there

![image](https://github.com/informatici/openhospital-ui/assets/2938553/0375c44b-21f6-4e40-800d-a35fc2d5aafe)
![image](https://github.com/informatici/openhospital-ui/assets/2938553/cdbe0edb-a466-4f90-a8ff-a89116105397)
![image](https://github.com/informatici/openhospital-ui/assets/2938553/58036dbd-4fea-453e-9f1d-577ffa767112)

Note: after the deletion the filter shows only "Type of operations"

![image](https://github.com/informatici/openhospital-ui/assets/2938553/844bee0d-6d35-4b6d-860d-ab1ecf570a9e)

2024-06-11 15:24 UTC, SilverD3 commented
> It performs a fake deletion, because OS is actually used and if I come back to the page the deleted record is still there

Are you using the mock server or the real backend? With the mock, it's normal the deleted type is reset after page/component refresh. But if you're using the real backend, that's where the issue would come from.

>Note: after the deletion the filter shows only "Type of operations"

Fixed!

2024-06-11 15:29 UTC, mwithi commented
it deletes

> > It performs a fake deletion, because OS is actually used and if I come back to the page the deleted record is still there
> 
> Are you using the mock server or the real backend? With the mock, it's normal the deleted type is reset after page/component refresh. But if you're using the real backend, that's where the issue would come from.

I always use the real backend.

> 
> > Note: after the deletion the filter shows only "Type of operations"
> 
> Fixed!

Thanks!

2024-06-12 15:02 UTC, mwithi approved these changes

2024-06-12 15:02 UTC, merged