OH2-294 | ATypes / Exams CRUD
informatici/openhospital-ui pull request #608
Opened 2024-06-12 09:49 UTC by loique70

2024-06-12 13:05 UTC, SilverD3 requested changes
The function looks good, I mean we can list/edit/add/delete exam types.
But I think you've duplicated the slice `src\state\examTypes`. I suggest to remove it and replace all references by the new state slice `src\state\types\exams`

2024-06-13 07:35 UTC, SteveGT96 requested changes

2024-06-13 07:35 UTC, SteveGT96 commented on src/components/accessories/admin/types/components/exams/ExamsTypes.tsx
> +                navigate("./new");
```suggestion
                navigate(PATHS.admin_exams_types_new);
```

2024-06-13 10:12 UTC, SilverD3 commented
Please fix conflits and take into consideration my [suggestion](https://github.com/informatici/openhospital-ui/pull/608#pullrequestreview-2112966554)

2024-06-14 22:46 UTC, mwithi approved these changes
LGTM. Thanks a lot!

2024-06-18 14:04 UTC, merged