OH2-321 | Types / Pregnant Treatment CRUD
informatici/openhospital-ui pull request #613
Opened 2024-06-15 10:17 UTC by loique70

2024-06-17 07:18 UTC, mwithi requested changes
I get this error
![image](https://github.com/informatici/openhospital-ui/assets/2938553/9b5cda25-d3f5-4dd8-a872-1a34eae23d6e)

2024-06-18 10:02 UTC, mwithi approved these changes

2024-06-18 10:03 UTC, mwithi requested changes
The edit form is not aligned

![image](https://github.com/informatici/openhospital-ui/assets/2938553/72502eb7-9237-4f1d-81b0-fde6b6e84388)

2024-06-18 13:45 UTC, SilverD3 requested changes
Make form fields responsive and use a comprehensive fake data, I mean one that reflects the pregnancy treatment types

2024-06-18 14:32 UTC, merged