OH2-355 | Tests / Add cypress e2e tests to cover diseases types (admin/types/diseases)
informatici/openhospital-ui pull request #628
Opened 2024-07-17 10:31 UTC by SilverD3

See OH2-355

2024-07-18 13:56 UTC, SteveGT96 requested changes

2024-07-18 13:56 UTC, SteveGT96 commented on cypress/integrations/admin_activities/types_activities/diseases_activities/manage_diseases_activity.cy.ts
> +      });
We should avoid naming variable that way. 
Could you make a refactoring like follows ?

```suggestion
      .then((query) => {
        expect(query.find("tbody tr").length).equal(1);
      });
```

2024-07-19 08:02 UTC, SilverD3 commented on cypress/integrations/admin_activities/types_activities/diseases_activities/manage_diseases_activity.cy.ts
> +      });
What's wrong with my implementation?

2024-07-19 08:45 UTC, SteveGT96 approved these changes

2024-07-19 14:03 UTC, mwithi approved these changes
Reviewed and approved by @SteveGT96

2024-07-19 14:03 UTC, merged