OH2-288 | Implement hospital infos edit
informatici/openhospital-ui pull request #675
Opened 2024-10-09 14:12 UTC by SteveGT96

See [OH2-288](https://openhospital.atlassian.net/browse/OH2-288)

[OH2-288]: https://openhospital.atlassian.net/browse/OH2-288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-10 16:22 UTC, SilverD3 requested changes
### General considerations

- Refreshing the page when I'm at `/admin/hospital/edit` redirect me back to `/admin`
- Integration tests are failing. Unable to save hospital data 
![failed-to-update-hospital](https://github.com/user-attachments/assets/ae564d3d-b62b-4c9c-8672-732baba01a41)
- Please scroll to the top when we click on "Edit hospital infos" button to let the user see form without needing to scroll up himself.

2024-10-10 16:22 UTC, SilverD3 commented on src/components/activities/adminActivity/SideMenu/SideMenu.tsx
> +              }}
Isn't it possible to do this with CSS classes rather than introducing this property?

2024-10-15 07:14 UTC, gasp approved these changes

2024-10-15 14:44 UTC, mwithi approved these changes
LGTM. Thanks a lot!

2024-10-15 14:44 UTC, merged