OH2-300 | Implement delete user feature
informatici/openhospital-ui pull request #681
Opened 2024-10-23 14:22 UTC by SteveGT96

See [OH2-300](https://openhospital.atlassian.net/browse/OH2-300)

2024-10-25 08:12 UTC, SilverD3 requested changes

2024-10-25 08:12 UTC, SilverD3 commented on src/components/accessories/admin/users/usersTable/UsersTable.tsx
> +    }
Show success message when the deletion is done

2024-10-25 10:36 UTC, SilverD3 approved these changes

2024-10-28 09:53 UTC, mwithi approved these changes
Reviewed and approved by @SilverD3

2024-10-28 09:53 UTC, merged