OH2-443 | Refactor admin forms reset/cancel actions
informatici/openhospital-ui pull request #706
Opened 2024-11-29 13:24 UTC by SteveGT96

See [OH2-443](https://openhospital.atlassian.net/browse/OH2-443)

2024-12-06 09:11 UTC, SilverD3 requested changes
The 'cancel button' could manage at the top level, I mean by the parent component (just like we're doing with the form title). This way, we keep this logic centralize and easy to maintain.

Furthermore, the 'cancel  button' actually looks like the button for the 'primary action' of the form, when it's for a secondary or even tertiary action. We could use the secondary color (grey, I think) or a less expressive one.

![Screenshot 2024-12-06 at 10-05-54 Open Hospital](https://github.com/user-attachments/assets/b50c82a7-3124-49af-9a29-d25ecbd8c90d)

Finally for the icon, I suggest to use the chevron left or the arrow left

2024-12-13 14:34 UTC, SteveGT96 commented
> The 'cancel button' could manage at the top level, I mean by the parent component (just like we're doing with the form title). This way, we keep this logic centralize and easy to maintain.
> 
> Furthermore, the 'cancel button' actually looks like the button for the 'primary action' of the form, when it's for a secondary or even tertiary action. We could use the secondary color (grey, I think) or a less expressive one.
> 
> ![Screenshot 2024-12-06 at 10-05-54 Open Hospital](https://private-user-images.githubusercontent.com/58907550/393178880-b50c82a7-3124-49af-9a29-d25ecbd8c90d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMDAwODgsIm5iZiI6MTczNDA5OTc4OCwicGF0aCI6Ii81ODkwNzU1MC8zOTMxNzg4ODAtYjUwYzgyYTctMzEyNC00OWFmLTlhMjktZDI1ZWNiZDhjOTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDE0MjMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNWUzMzI5OWZmY2NlYWM1Y2YyMDUwYTdkNjY4MWZhNjU1NzBhMDIwMTY4NzU4OWM3MzdlMDYzMWFhMzQzNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mUaaPZzVjzYAuD27igrkn06uiJVj7ZKgIww_R3-penU)
> 
> Finally for the icon, I suggest to use the chevron left or the arrow left

Agree for the refractoring and the styles. If the cancel/reset operation are OK, then let's move that refecatoring and styles in a separate issue(that will also inclue laboratories one).
Are you OK ?

2024-12-17 23:09 UTC, mwithi commented
It doesn't make much sense that when I click DISCARD, then the popup window is called "Cancel" an the OK (primary) button is for proceeding with the discard while the DISCARD (secondary) is to "discard the discard"... let's use "Back to edit" that is more compliant with what the button does:

![image](https://github.com/user-attachments/assets/44ec7530-834f-4070-86c4-d1b8641d2b7f)

Moreover, I think the above message should be shown also when the user tries to change page before saving:

![chrome-capture-2024-12-17](https://github.com/user-attachments/assets/5767376a-cd2b-4ccf-912c-0b35187ae565)

On the other hand, the RESET button, shows a popup correctly named "Reset", with a primary OK button for proceeding, and a "Back" (secondary) button for "canceling the resetting", that at least is more related with a "back" operation, but I would call it also here "Back to edit".

![image](https://github.com/user-attachments/assets/fafebf24-64c5-4c7e-b6d3-01d32b353fd8)

So in general in the popup:
- the popup should be titled like the button name that generated it
- the primary button in the popup should repeat the button name to reinforce the operation 
- the seconday button should always be "Back to edit" or "Cancel"

For the page itself, I agree with @SilverD3 that the "Discard" should not appear like a primary at the top, but I don't have better suggestions about it at the moment

2025-01-06 08:22 UTC, SteveGT96 commented
> It doesn't make much sense that when I click DISCARD, the popup window is called "Cancel" and the OK (primary) button is for proceeding with the discard while the DISCARD (secondary) is to "discard the discard"... let's use "Back to edit" that is more compliant with what the button does:
> 
> ![image](https://private-user-images.githubusercontent.com/2938553/396691724-44ec7530-834f-4070-86c4-d1b8641d2b7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNDk2ODMsIm5iZiI6MTczNjE0OTM4MywicGF0aCI6Ii8yOTM4NTUzLzM5NjY5MTcyNC00NGVjNzUzMC04MzRmLTQwNzAtODZjNC1kMWI4NjQxZDJiN2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDZUMDc0MzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGYzYTE3Mjk2MWI3YjlmOTY5OWYwYjY2ZGI5OGYyMjE3ZDM4ZjViZjgwZGFmOTMyYjU4NzljNzAzNjM4OTFiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.LZ2s5QMaddAYd1xvJ2uubJ0agiX9pm26MoIfuGaJt3A)
> 
> Moreover, I think the above message should be shown also when the user tries to change page before saving:
> 
> ![chrome-capture-2024-12-17](https://private-user-images.githubusercontent.com/2938553/396692367-5767376a-cd2b-4ccf-912c-0b35187ae565.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNDk2ODMsIm5iZiI6MTczNjE0OTM4MywicGF0aCI6Ii8yOTM4NTUzLzM5NjY5MjM2Ny01NzY3Mzc2YS1jZDJiLTRjY2YtOTEyYy0wYjM1MTg3YWU1NjUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDZUMDc0MzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTc2YzQ5ZjE5ZDQyMjc3YzBiNTUwYjBjMWRlM2IyOTg2OWJjMjljNzUwM2E1MzkwNDMyMDVkZGMzMThkNGY1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GyRO3R0p6uTbMusZNeRykJf9o4kl2vDhR7Xjp2C07_k) [ ![chrome-capture-2024-12-17](https://private-user-images.githubusercontent.com/2938553/396692367-5767376a-cd2b-4ccf-912c-0b35187ae565.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNDk2ODMsIm5iZiI6MTczNjE0OTM4MywicGF0aCI6Ii8yOTM4NTUzLzM5NjY5MjM2Ny01NzY3Mzc2YS1jZDJiLTRjY2YtOTEyYy0wYjM1MTg3YWU1NjUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDZUMDc0MzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTc2YzQ5ZjE5ZDQyMjc3YzBiNTUwYjBjMWRlM2IyOTg2OWJjMjljNzUwM2E1MzkwNDMyMDVkZGMzMThkNGY1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GyRO3R0p6uTbMusZNeRykJf9o4kl2vDhR7Xjp2C07_k) ](https://private-user-images.githubusercontent.com/2938553/396692367-5767376a-cd2b-4ccf-912c-0b35187ae565.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNDk2ODMsIm5iZiI6MTczNjE0OTM4MywicGF0aCI6Ii8yOTM4NTUzLzM5NjY5MjM2Ny01NzY3Mzc2YS1jZDJiLTRjY2YtOTEyYy0wYjM1MTg3YWU1NjUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDZUMDc0MzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTc2YzQ5ZjE5ZDQyMjc3YzBiNTUwYjBjMWRlM2IyOTg2OWJjMjljNzUwM2E1MzkwNDMyMDVkZGMzMThkNGY1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GyRO3R0p6uTbMusZNeRykJf9o4kl2vDhR7Xjp2C07_k) [ ](https://private-user-images.githubusercontent.com/2938553/396692367-5767376a-cd2b-4ccf-912c-0b35187ae565.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNDk2ODMsIm5iZiI6MTczNjE0OTM4MywicGF0aCI6Ii8yOTM4NTUzLzM5NjY5MjM2Ny01NzY3Mzc2YS1jZDJiLTRjY2YtOTEyYy0wYjM1MTg3YWU1NjUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDZUMDc0MzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTc2YzQ5ZjE5ZDQyMjc3YzBiNTUwYjBjMWRlM2IyOTg2OWJjMjljNzUwM2E1MzkwNDMyMDVkZGMzMThkNGY1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GyRO3R0p6uTbMusZNeRykJf9o4kl2vDhR7Xjp2C07_k)
> 
> On the other hand, the RESET button, shows a popup correctly named "Reset", with a primary OK button for proceeding, and a "Back" (secondary) button for "canceling the resetting", that at least is more related with a "back" operation, but I would call it also here "Back to edit".
> 
> ![image](https://private-user-images.githubusercontent.com/2938553/396693075-fafebf24-64c5-4c7e-b6d3-01d32b353fd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNDk2ODMsIm5iZiI6MTczNjE0OTM4MywicGF0aCI6Ii8yOTM4NTUzLzM5NjY5MzA3NS1mYWZlYmYyNC02NGM1LTRjN2UtYjZkMy0wMWQzMmIzNTNmZDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDZUMDc0MzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjIzZDhiM2Y1NGFiMDg3Zjg3NzUxY2ZmODUyNDI1OTgxNDdkYTMxZDM3MGFiZWU5NzkwNzU1Nzc3NTAzOGNlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.L_P5aNh5ds-JWVURTrAafZ7brB5WG-s98aKoBVbthqw)
> 
> So in general in the popup:
> 
> * the popup should be titled like the button name that generated it
> * the primary button in the popup should repeat the button name to reinforce the operation
> * the secondary button should always be "Back to edit" or "Cancel"
> 
> For the page itself, I agree with @SilverD3 that the "Discard" should not appear like a primary at the top, but I don't have better suggestions about it at the moment

Hi @mwithi  ! I've just updated labels as suggested !

2025-01-08 20:38 UTC, mwithi commented
> Hi @mwithi ! I've just updated labels as suggested !

Hi @SteveGT96 can you make also that if I was editing and I try to change page it triggers automatically the discharge event with related popup?

2025-01-09 07:10 UTC, SteveGT96 commented
Let me check that !

2025-01-09 15:39 UTC, SteveGT96 commented
> > Hi @mwithi ! I've just updated labels as suggested !
> 
> Hi @SteveGT96 can you make also that if I was editing and I try to change page it triggers automatically the discharge event with related popup?

Hi @mwithi  ! Could you review it again ?

2025-01-09 17:08 UTC, mwithi commented
> Hi @mwithi ! Could you review it again ?

I don't see changes yet about it:

![chrome-capture-2025-1-9](https://github.com/user-attachments/assets/3b20ab3b-14d2-4bfd-8c6b-c6a066f079a2)

2025-01-10 07:37 UTC, SteveGT96 commented
> > Hi @mwithi ! Could you review it again ?
> 
> I don't see changes yet about it:
> 
> ![chrome-capture-2025-1-9](https://private-user-images.githubusercontent.com/2938553/401632636-3b20ab3b-14d2-4bfd-8c6b-c6a066f079a2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0OTQ4MTEsIm5iZiI6MTczNjQ5NDUxMSwicGF0aCI6Ii8yOTM4NTUzLzQwMTYzMjYzNi0zYjIwYWIzYi0xNGQyLTRiZmQtOGM2Yi1jNmEwNjZmMDc5YTIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTBUMDczNTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGYxM2M2YzA0ZTFlZjliNzQ0MzQxNmU5YWNhYTgwNmQyNjQ2ZjA2NjczNTRhMDJhNGU5Y2Q3NzQ2YTA1MmUwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cQhUqElhQBoofea2_w8mTM4ZBnnn6BFAeciS84OUolk) [ ![chrome-capture-2025-1-9](https://private-user-images.githubusercontent.com/2938553/401632636-3b20ab3b-14d2-4bfd-8c6b-c6a066f079a2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0OTQ4MTEsIm5iZiI6MTczNjQ5NDUxMSwicGF0aCI6Ii8yOTM4NTUzLzQwMTYzMjYzNi0zYjIwYWIzYi0xNGQyLTRiZmQtOGM2Yi1jNmEwNjZmMDc5YTIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTBUMDczNTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGYxM2M2YzA0ZTFlZjliNzQ0MzQxNmU5YWNhYTgwNmQyNjQ2ZjA2NjczNTRhMDJhNGU5Y2Q3NzQ2YTA1MmUwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cQhUqElhQBoofea2_w8mTM4ZBnnn6BFAeciS84OUolk) ](https://private-user-images.githubusercontent.com/2938553/401632636-3b20ab3b-14d2-4bfd-8c6b-c6a066f079a2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0OTQ4MTEsIm5iZiI6MTczNjQ5NDUxMSwicGF0aCI6Ii8yOTM4NTUzLzQwMTYzMjYzNi0zYjIwYWIzYi0xNGQyLTRiZmQtOGM2Yi1jNmEwNjZmMDc5YTIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTBUMDczNTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGYxM2M2YzA0ZTFlZjliNzQ0MzQxNmU5YWNhYTgwNmQyNjQ2ZjA2NjczNTRhMDJhNGU5Y2Q3NzQ2YTA1MmUwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cQhUqElhQBoofea2_w8mTM4ZBnnn6BFAeciS84OUolk) [ ](https://private-user-images.githubusercontent.com/2938553/401632636-3b20ab3b-14d2-4bfd-8c6b-c6a066f079a2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0OTQ4MTEsIm5iZiI6MTczNjQ5NDUxMSwicGF0aCI6Ii8yOTM4NTUzLzQwMTYzMjYzNi0zYjIwYWIzYi0xNGQyLTRiZmQtOGM2Yi1jNmEwNjZmMDc5YTIuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTBUMDczNTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGYxM2M2YzA0ZTFlZjliNzQ0MzQxNmU5YWNhYTgwNmQyNjQ2ZjA2NjczNTRhMDJhNGU5Y2Q3NzQ2YTA1MmUwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cQhUqElhQBoofea2_w8mTM4ZBnnn6BFAeciS84OUolk)

You're right. I've just tested the solutions with app bar navigation links and back button.

I've added a quick fix, it's OK now !

Could  you confirm @mwithi  ?

2025-01-10 12:36 UTC, mwithi commented
> Could you confirm @mwithi ?

Yes! Well done! I think we can merge this!

One questions: this works only for the admin section, right? what about all other forms in other sections?

2025-01-10 13:17 UTC, SteveGT96 commented
> > Could you confirm @mwithi ?
> 
> Yes! Well done! I think we can merge this!
> 
> One questions: this works only for the admin section, right? what about all other forms in other sections?

We could handle other parts in separate issues !

2025-01-10 15:38 UTC, mwithi commented
> > > Could you confirm @mwithi ?
> > 
> > 
> > Yes! Well done! I think we can merge this!
> > One questions: this works only for the admin section, right? what about all other forms in other sections?
> 
> We could handle other parts in separate issues !

Sure, what I'm asking is that they have different logic or the same.

2025-01-10 16:25 UTC, SteveGT96 commented
I think actually other parts don"t have the same logic like the one in admin section. Should they have the same behaviour/logic ? If yes then we'll hande that in separated issues.

2025-01-11 08:10 UTC, SilverD3 commented
> @SilverD3 do you approve the code part?

Still reviewing. There are a lot of changed file

2025-01-11 08:26 UTC, SilverD3 reviewed
I still believe that the "cancel form edit" logic can be centralized and manage at a top level, instead of implementing the same logic in all "form components" of the admin section.

I notice that all pages of the admin section are rendered in the component `AdminActivityContent` (`src\components\activities\adminActivity\AdminActivityContent\AdminActivityContent.tsx`). We can centralize the "form cancel" logic in this component, and if not suitable, we can still look for a "higher level" component. 

This way, we avoid a lot of code duplication.

2025-01-11 08:26 UTC, SilverD3 commented on cypress/integrations/admin_activities/diseases_activities/add_disease_activity.cy.ts
> +    cy.dataCy("approve-dialog").click().click();
Is this a normal behavior? I mean, clicking twice?

2025-01-13 07:26 UTC, SteveGT96 commented on cypress/integrations/admin_activities/diseases_activities/add_disease_activity.cy.ts
> +    cy.dataCy("approve-dialog").click().click();
Some time in e2e tests simple clicks don't complete, causing tests to fail. This is a  quick fix !

2025-01-13 07:28 UTC, SteveGT96 commented
> I still believe that the "cancel form edit" logic can be centralized and manage at a top level, instead of implementing the same logic in all "form components" of the admin section.
> 
> I notice that all pages of the admin section are rendered in the component `AdminActivityContent` (`src\components\activities\adminActivity\AdminActivityContent\AdminActivityContent.tsx`). We can centralize the "form cancel" logic in this component, and if not suitable, we can still look for a "higher level" component.
> 
> This way, we avoid a lot of code duplication.

Of cause ! This is to be addressed in a separate issue !

2025-01-13 07:45 UTC, SilverD3 commented
Please can you create this or those issues, before we merge this PR?

2025-01-13 14:45 UTC, SteveGT96 commented
> I still believe that the "cancel form edit" logic can be centralized and manage at a top level, instead of implementing the same logic in all "form components" of the admin section.
> 
> I notice that all pages of the admin section are rendered in the component `AdminActivityContent` (`src\components\activities\adminActivity\AdminActivityContent\AdminActivityContent.tsx`). We can centralize the "form cancel" logic in this component, and if not suitable, we can still look for a "higher level" component.
> 
> This way, we avoid a lot of code duplication.

Just updated !

2025-01-14 15:29 UTC, mwithi commented
> Just updated !

@SilverD3 is it ok now?

2025-01-14 16:10 UTC, SilverD3 reviewed
![Screenshot 2025-01-14 at 17-06-39 Open Hospital](https://github.com/user-attachments/assets/ef6c8965-d396-4970-ac3f-6c84d2ee826b)
The primary button label, for now `Discard` for English, can be a bit confusing. I suggest to use `Yes, discard` as label instead

2025-01-14 16:31 UTC, SilverD3 commented
I'm also getting a strange behavior. Look at the video

https://github.com/user-attachments/assets/8063c8e1-a84b-4fc6-8269-f22301bb730c

2025-01-24 18:24 UTC, mwithi commented
LGTM! @SilverD3 ?

2025-01-31 14:15 UTC, SilverD3 commented
The issue with the discard button has been fixed.

> The primary button label, for now `Discard` for English, can be a bit confusing. I suggest to use `Yes, discard` as label instead

But not the label. I also noticed that when I click on "form reset" button, the label of the primary button is `Reset` and for the secondary button is `Back to edit`. I suggest `Yes, reset` for the primary button and `No, keep editing` or `No, continue editing`

2025-01-31 14:27 UTC, SteveGT96 commented
> The issue with the discard button has been fixed.
> 
> > The primary button label, for now `Discard` for English, can be a bit confusing. I suggest to use `Yes, discard` as label instead
> 
> But not the label. I also noticed that when I click on "form reset" button, the label of the primary button is `Reset` and for the secondary button is `Back to edit`. I suggest `Yes, reset` for the primary button and `No, keep editing` or `No, continue editing`

@mwithi  should we finally keep ? The actual labels were your suggestion.

2025-01-31 23:16 UTC, mwithi commented
> @mwithi should we finally keep ? The actual labels were your suggestion.

I find the actual ones less verbose although the ones from @SilverD3 more clear, so as you wish guys.

2025-04-11 09:56 UTC, SilverD3 approved these changes

2025-04-11 13:31 UTC, mwithi approved these changes
Reviewed and approved by @SilverD3

2025-04-11 13:32 UTC, merged