OH2-417 | Fix dashboard widgets and refactor size change handler
informatici/openhospital-ui pull request #708
Opened 2024-12-03 13:53 UTC by SteveGT96

See [OH2-417](https://openhospital.atlassian.net/browse/OH2-417)

2024-12-06 08:34 UTC, SilverD3 requested changes
The problem seems to have been solved, but the pie charts are now oval instead of circular.

![Screenshot 2024-12-06 at 09-26-43 Open Hospital](https://github.com/user-attachments/assets/a66bf1e8-61cd-4617-b884-5669951b124c)

2024-12-07 15:07 UTC, mwithi commented
It seems that the aspect-ratio is not maitained:

![chrome-capture-2024-12-7](https://github.com/user-attachments/assets/c9b6765e-8af1-4c97-a25a-62579442bc30)

2024-12-09 07:44 UTC, SteveGT96 commented
> It seems that the aspect-ratio is not maitained:
> 
> ![chrome-capture-2024-12-7](https://private-user-images.githubusercontent.com/2938553/393526272-c9b6765e-8af1-4c97-a25a-62579442bc30.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MjkwMzQsIm5iZiI6MTczMzcyODczNCwicGF0aCI6Ii8yOTM4NTUzLzM5MzUyNjI3Mi1jOWI2NzY1ZS04YWYxLTRjOTctYTI1YS02MjU3OTQ0MmJjMzAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMDcxODU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmNjOWM2NDRiYmI4MTUwYzFmODM1YmY2Y2JlNmZkMjA2NTRhOWYzYjZjNWY2NzhlNzdlOThjODM1ZGMxYTA4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SxkBCdgZjXwN5MJxbA-pNACG-fdOiGDo4fvAAhozBM0) [ ![chrome-capture-2024-12-7](https://private-user-images.githubusercontent.com/2938553/393526272-c9b6765e-8af1-4c97-a25a-62579442bc30.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MjkwMzQsIm5iZiI6MTczMzcyODczNCwicGF0aCI6Ii8yOTM4NTUzLzM5MzUyNjI3Mi1jOWI2NzY1ZS04YWYxLTRjOTctYTI1YS02MjU3OTQ0MmJjMzAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMDcxODU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmNjOWM2NDRiYmI4MTUwYzFmODM1YmY2Y2JlNmZkMjA2NTRhOWYzYjZjNWY2NzhlNzdlOThjODM1ZGMxYTA4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SxkBCdgZjXwN5MJxbA-pNACG-fdOiGDo4fvAAhozBM0) ](https://private-user-images.githubusercontent.com/2938553/393526272-c9b6765e-8af1-4c97-a25a-62579442bc30.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MjkwMzQsIm5iZiI6MTczMzcyODczNCwicGF0aCI6Ii8yOTM4NTUzLzM5MzUyNjI3Mi1jOWI2NzY1ZS04YWYxLTRjOTctYTI1YS02MjU3OTQ0MmJjMzAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMDcxODU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmNjOWM2NDRiYmI4MTUwYzFmODM1YmY2Y2JlNmZkMjA2NTRhOWYzYjZjNWY2NzhlNzdlOThjODM1ZGMxYTA4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SxkBCdgZjXwN5MJxbA-pNACG-fdOiGDo4fvAAhozBM0) [ ](https://private-user-images.githubusercontent.com/2938553/393526272-c9b6765e-8af1-4c97-a25a-62579442bc30.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MjkwMzQsIm5iZiI6MTczMzcyODczNCwicGF0aCI6Ii8yOTM4NTUzLzM5MzUyNjI3Mi1jOWI2NzY1ZS04YWYxLTRjOTctYTI1YS02MjU3OTQ0MmJjMzAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMDcxODU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmNjOWM2NDRiYmI4MTUwYzFmODM1YmY2Y2JlNmZkMjA2NTRhOWYzYjZjNWY2NzhlNzdlOThjODM1ZGMxYTA4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SxkBCdgZjXwN5MJxbA-pNACG-fdOiGDo4fvAAhozBM0)
Hello @mwithi  ! Just put an update !

2024-12-09 12:54 UTC, mwithi commented
> Hello @mwithi ! Just put an update !
with sizes bigger than default one is ok, for smaller sizes it is still out of ratio:

![image](https://github.com/user-attachments/assets/de91e5cb-cd8b-4065-9ef3-7295e7322ff9)

2024-12-09 14:27 UTC, SilverD3 commented
![Screenshot 2024-12-09 at 10-44-04 Open Hospital](https://github.com/user-attachments/assets/722cc972-fcae-47da-9edf-4e13868a9ad3)

'Min' and 'max' sizes of widgets have changed and they're still looking flatten.
Furthermore, now they're not filling all the available space in their container

2024-12-17 20:42 UTC, mwithi commented
I guess you already tested it, so maybe there is something that depends by the user screen.

After many tries, I found that any size is good but the ones below the default width (default height seems also the minimum):

![chrome-capture-2024-12-17](https://github.com/user-attachments/assets/2365eb2b-a295-4101-ba86-ac14170aea4e)

2025-01-06 07:42 UTC, SteveGT96 commented
> I guess you already tested it, so maybe there is something that depends by the user screen.
> 
> After many tries, I found that any size is good but the ones below the default width (default height seems also the minimum):
> 
> ![chrome-capture-2024-12-17](https://private-user-images.githubusercontent.com/2938553/396659573-2365eb2b-a295-4101-ba86-ac14170aea4e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNDk1MzEsIm5iZiI6MTczNjE0OTIzMSwicGF0aCI6Ii8yOTM4NTUzLzM5NjY1OTU3My0yMzY1ZWIyYi1hMjk1LTQxMDEtYmE4Ni1hYzE0MTcwYWVhNGUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDZUMDc0MDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmNhMDIxZjU1MDJiMjUxZWI0OTY1NGRiMGU0YzY1YjI0OWQxMTMxZmU1ODgwNjNlOTQyYmI4MzFlNTdkZDkzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.BKxG_mMJ_E7yEcfc_Yn1tsdBXnl8cV7IOSHzl1OevL4) [ ![chrome-capture-2024-12-17](https://private-user-images.githubusercontent.com/2938553/396659573-2365eb2b-a295-4101-ba86-ac14170aea4e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNDk1MzEsIm5iZiI6MTczNjE0OTIzMSwicGF0aCI6Ii8yOTM4NTUzLzM5NjY1OTU3My0yMzY1ZWIyYi1hMjk1LTQxMDEtYmE4Ni1hYzE0MTcwYWVhNGUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDZUMDc0MDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmNhMDIxZjU1MDJiMjUxZWI0OTY1NGRiMGU0YzY1YjI0OWQxMTMxZmU1ODgwNjNlOTQyYmI4MzFlNTdkZDkzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.BKxG_mMJ_E7yEcfc_Yn1tsdBXnl8cV7IOSHzl1OevL4) ](https://private-user-images.githubusercontent.com/2938553/396659573-2365eb2b-a295-4101-ba86-ac14170aea4e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNDk1MzEsIm5iZiI6MTczNjE0OTIzMSwicGF0aCI6Ii8yOTM4NTUzLzM5NjY1OTU3My0yMzY1ZWIyYi1hMjk1LTQxMDEtYmE4Ni1hYzE0MTcwYWVhNGUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDZUMDc0MDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmNhMDIxZjU1MDJiMjUxZWI0OTY1NGRiMGU0YzY1YjI0OWQxMTMxZmU1ODgwNjNlOTQyYmI4MzFlNTdkZDkzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.BKxG_mMJ_E7yEcfc_Yn1tsdBXnl8cV7IOSHzl1OevL4) [ ](https://private-user-images.githubusercontent.com/2938553/396659573-2365eb2b-a295-4101-ba86-ac14170aea4e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNDk1MzEsIm5iZiI6MTczNjE0OTIzMSwicGF0aCI6Ii8yOTM4NTUzLzM5NjY1OTU3My0yMzY1ZWIyYi1hMjk1LTQxMDEtYmE4Ni1hYzE0MTcwYWVhNGUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDZUMDc0MDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmNhMDIxZjU1MDJiMjUxZWI0OTY1NGRiMGU0YzY1YjI0OWQxMTMxZmU1ODgwNjNlOTQyYmI4MzFlNTdkZDkzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.BKxG_mMJ_E7yEcfc_Yn1tsdBXnl8cV7IOSHzl1OevL4)

Hi @mwithi  ! What do you suggest ?

2025-01-08 15:55 UTC, SilverD3 approved these changes
LGTM! The chart animation is a little bit slow, though. But it's too bad

2025-01-08 23:36 UTC, mwithi commented
> LGTM! The chart animation is a little bit slow, though. But it's too bad

I guess you meant "it's NOT too bad" 😄. LGTM!
(but we have to do something for the slow animation...)

2025-01-08 23:37 UTC, mwithi approved these changes

2025-01-08 23:37 UTC, merged